### ISSUE TITLE
Feature Request: Managed Updates

### ISSUE THREAD

**Issue by azurecurve** [TukuToi/tukutoi-contact-form#6]
It would be really good to have [Update Manager](https://directory.classicpress.net/plugins/update-manager) integrated in order to manage notifications of available update and installation of update on sites.

**Comment by smileBeda** [comment]
I am reluctant to do this because... de facto this is a job of the CMS. Also actually I could just throw this plugin onto the WP Repo solving this issue (all my plugins do that actually, they are both on CP and WP repo, when officially ready for)

But I will look into how much work it would be to integrate it.

**Comment by azurecurve** [comment]
Adding Update Manager is easy to do, but you need to be running an update server.

If it is submitted to the W repo then that would provide the update functionality I'd prefer to have.

**Comment by smileBeda** [comment]
Yeah, though so. I was confused after reading the readme there, as it said I can serve updates from Git but then asked me to install the plugin, thus a server is needed

I don't think this is smart in general. We want to make a sort of "trusted" update source. if we have 90 CP Plugins with 90 different servers, who knows what clients/users will receive at the end. I mean - I control my servers, but do others? Now if (I or others) have an update server to ship updates to users... and it gets hacked. Good night with that.

Less likely to happen on WP Repo or (once we have it) CP repo, and if, then its on them, not on me - who couldn't afford the legal consequences of such a breach.

Closing here, and pushing to WP as soon I can call the plugin somewhat acceptably stable.
